"""
AI理解支援引用文献統合機能 v4.0 テスト

新機能の包括的なテストを提供します。
"""

import unittest
import tempfile
import os
from pathlib import Path
from datetime import datetime
from unittest.mock import patch, MagicMock

# テスト対象モジュールのインポート
from modules.ai_citation_support.data_structures import (
    CitationMapping, CitationInfo, AIReadableDocument, MappingStatistics
)
from modules.ai_citation_support.citation_mapping_engine import CitationMappingEngine
from modules.ai_citation_support.citation_resolver import CitationResolver
from modules.ai_citation_support.ai_assistant_file_generator import AIAssistantFileGenerator
from modules.ai_citation_support.ai_mapping_workflow import AIMappingWorkflow


class TestDataStructures(unittest.TestCase):
    """データ構造のテスト"""
    
    def test_citation_mapping_creation(self):
        """CitationMapping作成のテスト"""
        mapping = CitationMapping(
            references_file="/test/references.bib",
            index_map={1: "smith2023", 2: "doe2024"},
            last_updated=datetime.now(),
            mapping_version="1.0",
            total_citations=2
        )
        
        self.assertEqual(mapping.total_citations, 2)
        self.assertEqual(mapping.index_map[1], "smith2023")
        self.assertEqual(mapping.mapping_version, "1.0")
    
    def test_citation_mapping_yaml_conversion(self):
        """CitationMappingのYAML変換テスト"""
        mapping = CitationMapping(
            references_file="/test/references.bib",
            index_map={1: "smith2023", 2: "doe2024"},
            last_updated=datetime(2024, 1, 1, 12, 0, 0),
            mapping_version="1.0",
            total_citations=2
        )
        
        yaml_dict = mapping.to_yaml_dict()
        self.assertIn('references_file', yaml_dict)
        self.assertIn('index_map', yaml_dict)
        self.assertEqual(yaml_dict['total_citations'], 2)
        
        # 逆変換テスト
        restored_mapping = CitationMapping.from_yaml_dict(yaml_dict)
        self.assertEqual(restored_mapping.total_citations, 2)
        self.assertEqual(restored_mapping.index_map[1], "smith2023")
    
    def test_citation_info_reference_line(self):
        """CitationInfoのReference Line生成テスト"""
        citation = CitationInfo(
            number=1,
            citation_key="smith2023",
            title="Test Paper",
            authors="Smith, J. & Doe, A.",
            year=2023,
            journal="Test Journal",
            volume="10",
            pages="1-10",
            doi="10.1000/test",
            context="This paper shows [1] that..."
        )
        
        reference_line = citation.to_reference_line()
        self.assertIn("[1] →", reference_line)
        self.assertIn("Smith, J. & Doe, A.", reference_line)
        self.assertIn("(2023)", reference_line)
        self.assertIn("Test Paper", reference_line)
        self.assertIn("DOI: 10.1000/test", reference_line)
        self.assertIn("Context", reference_line)
    
    def test_ai_readable_document_markdown(self):
        """AIReadableDocumentのMarkdown生成テスト"""
        document = AIReadableDocument(
            original_file="/test/paper.md",
            references_file="/test/references.bib",
            citation_table="[1] → Test Citation",
            paper_content="# Test Paper\n\nContent [1].",
            generation_timestamp=datetime(2024, 1, 1, 12, 0, 0),
            total_citations=1
        )
        
        markdown = document.to_markdown()
        self.assertIn("# paper", markdown)
        self.assertIn("Citation Reference Table", markdown)
        self.assertIn("Paper Content", markdown)
        self.assertIn("[1] → Test Citation", markdown)
        self.assertIn("Generated by ObsClippingsManager v4.0", markdown)


class TestCitationMappingEngine(unittest.TestCase):
    """CitationMappingEngineのテスト"""
    
    def setUp(self):
        """テスト前の準備"""
        self.temp_dir = tempfile.mkdtemp()
        self.markdown_file = os.path.join(self.temp_dir, "test.md")
        self.bib_file = os.path.join(self.temp_dir, "references.bib")
        
        # テスト用Markdownファイル作成
        with open(self.markdown_file, 'w', encoding='utf-8') as f:
            f.write("""# Test Paper

This research [1] demonstrates that cancer cells [2],[3] are important.
Recent studies \\[[4]\\] also show similar results.
""")
        
        # テスト用BibTeXファイル作成
        with open(self.bib_file, 'w', encoding='utf-8') as f:
            f.write("""@article{smith2023,
  title={First Paper},
  author={Smith, John},
  year={2023}
}

@article{doe2024,
  title={Second Paper},
  author={Doe, Jane},
  year={2024}
}

@article{brown2022,
  title={Third Paper},
  author={Brown, Bob},
  year={2022}
}

@article{wilson2021,
  title={Fourth Paper},
  author={Wilson, Will},
  year={2021}
}
""")
    
    def tearDown(self):
        """テスト後の清理"""
        import shutil
        shutil.rmtree(self.temp_dir)
    
    def test_citation_mapping_creation(self):
        """引用マッピング作成のテスト"""
        engine = CitationMappingEngine()
        mapping = engine.create_citation_mapping(self.markdown_file, self.bib_file)
        
        self.assertEqual(mapping.total_citations, 4)
        self.assertIn(1, mapping.index_map)
        self.assertIn(2, mapping.index_map)
        self.assertIn(3, mapping.index_map)
        self.assertIn(4, mapping.index_map)
        
        # citation_keyの順序確認
        self.assertEqual(mapping.index_map[1], "smith2023")
        self.assertEqual(mapping.index_map[2], "doe2024")
        self.assertEqual(mapping.index_map[3], "brown2022")
        self.assertEqual(mapping.index_map[4], "wilson2021")
    
    def test_yaml_header_update(self):
        """YAMLヘッダー更新のテスト"""
        engine = CitationMappingEngine()
        mapping = engine.create_citation_mapping(self.markdown_file, self.bib_file)
        
        # YAMLヘッダーを更新
        success = engine.update_yaml_header(self.markdown_file, mapping)
        self.assertTrue(success)
        
        # ファイル内容確認
        with open(self.markdown_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        self.assertIn("---", content)
        self.assertIn("citation_mapping:", content)
        self.assertIn("index_map:", content)
        self.assertIn("references_file:", content)
    
    def test_citation_number_extraction(self):
        """引用番号抽出のテスト"""
        engine = CitationMappingEngine()
        citation_numbers = engine._extract_citation_numbers(self.markdown_file)
        
        self.assertEqual(len(citation_numbers), 4)
        self.assertIn(1, citation_numbers)
        self.assertIn(2, citation_numbers)
        self.assertIn(3, citation_numbers)
        self.assertIn(4, citation_numbers)


class TestCitationResolver(unittest.TestCase):
    """CitationResolverのテスト"""
    
    def setUp(self):
        """テスト前の準備"""
        self.temp_dir = tempfile.mkdtemp()
        self.markdown_file = os.path.join(self.temp_dir, "test.md")
        self.bib_file = os.path.join(self.temp_dir, "references.bib")
        
        # YAMLヘッダー付きMarkdownファイル作成
        with open(self.markdown_file, 'w', encoding='utf-8') as f:
            f.write("""---
citation_mapping:
  references_file: {}
  index_map:
    1: smith2023
    2: doe2024
  last_updated: '2024-01-01T12:00:00'
  mapping_version: '1.0'
  total_citations: 2
---

# Test Paper

This research [1] demonstrates that cancer cells [2] are important.
""".format(self.bib_file.replace('\\', '\\\\')))
        
        # BibTeXファイル作成
        with open(self.bib_file, 'w', encoding='utf-8') as f:
            f.write("""@article{smith2023,
  title={Novel Method for Cancer Analysis},
  author={Smith, John and Brown, Alice},
  year={2023},
  journal={Nature Medicine},
  volume={29},
  pages={123-130},
  doi={10.1038/test.2023}
}

@article{doe2024,
  title={Advanced Treatment Approaches},
  author={Doe, Jane},
  year={2024},
  journal={Cell},
  volume={187},
  pages={45-60},
  doi={10.1016/test.2024}
}
""")
    
    def tearDown(self):
        """テスト後の清理"""
        import shutil
        shutil.rmtree(self.temp_dir)
    
    def test_citation_resolution(self):
        """引用解決のテスト"""
        resolver = CitationResolver()
        citation_info = resolver.resolve_citation(1, self.markdown_file)
        
        self.assertIsNotNone(citation_info)
        self.assertEqual(citation_info.number, 1)
        self.assertEqual(citation_info.citation_key, "smith2023")
        self.assertEqual(citation_info.title, "Novel Method for Cancer Analysis")
        self.assertEqual(citation_info.year, 2023)
        self.assertIn("Smith", citation_info.authors)
        self.assertEqual(citation_info.doi, "10.1038/test.2023")
    
    def test_batch_citation_resolution(self):
        """バッチ引用解決のテスト"""
        resolver = CitationResolver()
        results = resolver.batch_resolve_citations([1, 2], self.markdown_file)
        
        self.assertEqual(len(results), 2)
        self.assertIn(1, results)
        self.assertIn(2, results)
        
        # 1番目の引用
        citation1 = results[1]
        self.assertEqual(citation1.citation_key, "smith2023")
        self.assertEqual(citation1.year, 2023)
        
        # 2番目の引用
        citation2 = results[2]
        self.assertEqual(citation2.citation_key, "doe2024")
        self.assertEqual(citation2.year, 2024)
    
    def test_context_extraction(self):
        """文脈抽出のテスト"""
        resolver = CitationResolver()
        context = resolver.extract_citation_context(self.markdown_file, 1)
        
        self.assertIn("research", context.lower())
        self.assertIn("[1]", context)


class TestAIAssistantFileGenerator(unittest.TestCase):
    """AIAssistantFileGeneratorのテスト"""
    
    def setUp(self):
        """テスト前の準備"""
        self.temp_dir = tempfile.mkdtemp()
        self.markdown_file = os.path.join(self.temp_dir, "test.md")
        self.bib_file = os.path.join(self.temp_dir, "references.bib")
        
        # マッピング済みMarkdownファイル作成
        with open(self.markdown_file, 'w', encoding='utf-8') as f:
            f.write("""---
citation_mapping:
  references_file: {}
  index_map:
    1: smith2023
    2: doe2024
  last_updated: '2024-01-01T12:00:00'
  mapping_version: '1.0'
  total_citations: 2
---

# Test Paper

This research [1] demonstrates that cancer cells [2] are important mediators.
""".format(self.bib_file.replace('\\', '\\\\')))
        
        # BibTeXファイル作成
        with open(self.bib_file, 'w', encoding='utf-8') as f:
            f.write("""@article{smith2023,
  title={Novel Method for Cancer Analysis},
  author={Smith, John},
  year={2023},
  journal={Nature Medicine},
  doi={10.1038/test.2023}
}

@article{doe2024,
  title={Advanced Treatment Approaches},
  author={Doe, Jane},
  year={2024},
  journal={Cell},
  doi={10.1016/test.2024}
}
""")
    
    def tearDown(self):
        """テスト後の清理"""
        import shutil
        shutil.rmtree(self.temp_dir)
    
    def test_ai_file_generation(self):
        """AI用ファイル生成のテスト"""
        generator = AIAssistantFileGenerator()
        result = generator.generate_ai_readable_file(self.markdown_file)
        
        self.assertTrue(result.success)
        self.assertIsNotNone(result.output_file)
        self.assertTrue(os.path.exists(result.output_file))
        
        # 生成されたファイル内容確認
        with open(result.output_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        self.assertIn("Citation Reference Table", content)
        self.assertIn("Paper Content", content)
        self.assertIn("[1] →", content)
        self.assertIn("[2] →", content)
        self.assertIn("Smith, John", content)
        self.assertIn("Doe, Jane", content)
        self.assertIn("Generated by ObsClippingsManager v4.0", content)
    
    def test_citation_preview(self):
        """引用プレビュー生成のテスト"""
        generator = AIAssistantFileGenerator()
        preview = generator.generate_citation_preview(self.markdown_file, max_citations=2)
        
        self.assertIn("Citation Preview", preview)
        self.assertIn("[1]", preview)
        self.assertIn("[2]", preview)
        self.assertIn("Smith", preview)
        self.assertIn("Doe", preview)
    
    def test_file_quality_validation(self):
        """ファイル品質検証のテスト"""
        generator = AIAssistantFileGenerator()
        result = generator.generate_ai_readable_file(self.markdown_file)
        self.assertTrue(result.success)
        
        # 品質検証実行
        quality_ok, issues = generator.validate_ai_file_quality(result.output_file)
        self.assertTrue(quality_ok)
        self.assertEqual(len(issues), 0)


class TestAIMappingWorkflow(unittest.TestCase):
    """AIMappingWorkflowのテスト"""
    
    def setUp(self):
        """テスト前の準備"""
        self.temp_dir = tempfile.mkdtemp()
        self.markdown_file = os.path.join(self.temp_dir, "test.md")
        self.bib_file = os.path.join(self.temp_dir, "references.bib")
        
        # Markdownファイル作成
        with open(self.markdown_file, 'w', encoding='utf-8') as f:
            f.write("""# Test Paper

This research [1] demonstrates that cancer cells [2] are important.
""")
        
        # BibTeXファイル作成
        with open(self.bib_file, 'w', encoding='utf-8') as f:
            f.write("""@article{smith2023,
  title={Novel Method for Cancer Analysis},
  author={Smith, John},
  year={2023}
}

@article{doe2024,
  title={Advanced Treatment Approaches},
  author={Doe, Jane},
  year={2024}
}
""")
    
    def tearDown(self):
        """テスト後の清理"""
        import shutil
        shutil.rmtree(self.temp_dir)
    
    def test_ai_mapping_workflow_execution(self):
        """AI理解支援ワークフロー実行のテスト"""
        workflow = AIMappingWorkflow()
        result = workflow.execute_ai_mapping(
            self.markdown_file, 
            self.bib_file,
            generate_ai_file=True
        )
        
        self.assertTrue(result.success)
        self.assertIsNotNone(result.output_file)
        self.assertTrue(os.path.exists(result.output_file))
        self.assertIsNotNone(result.statistics)
        self.assertEqual(result.statistics.total_citations_mapped, 2)
    
    def test_mapping_only_workflow(self):
        """マッピングのみワークフローのテスト"""
        workflow = AIMappingWorkflow()
        result = workflow.execute_ai_mapping(
            self.markdown_file, 
            self.bib_file,
            generate_ai_file=False
        )
        
        self.assertTrue(result.success)
        self.assertEqual(result.output_file, "")  # AI用ファイルは生成されない
        self.assertIsNotNone(result.statistics)
    
    def test_dry_run_execution(self):
        """ドライラン実行のテスト"""
        workflow = AIMappingWorkflow()
        dry_run_report = workflow.dry_run_ai_mapping(self.markdown_file, self.bib_file)
        
        self.assertIn("Dry Run Analysis", dry_run_report)
        self.assertIn("Citations Found: 2", dry_run_report)
        self.assertIn("[1] → smith2023", dry_run_report)
        self.assertIn("[2] → doe2024", dry_run_report)
    
    def test_batch_execution(self):
        """バッチ実行のテスト"""
        # 2つ目のファイルペア作成
        markdown_file2 = os.path.join(self.temp_dir, "test2.md")
        with open(markdown_file2, 'w', encoding='utf-8') as f:
            f.write("# Test Paper 2\n\nThis shows [1] results.")
        
        workflow = AIMappingWorkflow()
        file_pairs = [
            (self.markdown_file, self.bib_file),
            (markdown_file2, self.bib_file)
        ]
        
        results = workflow.batch_execute_ai_mapping(file_pairs, generate_ai_files=True)
        
        self.assertEqual(len(results), 2)
        self.assertIn(self.markdown_file, results)
        self.assertIn(markdown_file2, results)
        
        # 両方とも成功していることを確認
        self.assertTrue(results[self.markdown_file].success)
        self.assertTrue(results[markdown_file2].success)
    
    def test_workflow_statistics(self):
        """ワークフロー統計のテスト"""
        workflow = AIMappingWorkflow()
        
        # 初期統計確認
        initial_stats = workflow.get_workflow_statistics()
        self.assertEqual(initial_stats['total_files_processed'], 0)
        
        # ワークフロー実行
        result = workflow.execute_ai_mapping(
            self.markdown_file, 
            self.bib_file,
            generate_ai_file=True
        )
        self.assertTrue(result.success)
        
        # 更新された統計確認
        updated_stats = workflow.get_workflow_statistics()
        self.assertEqual(updated_stats['total_files_processed'], 1)
        self.assertEqual(updated_stats['successful_mappings'], 1)
        self.assertEqual(updated_stats['successful_generations'], 1)
        self.assertEqual(updated_stats['mapping_success_rate'], 1.0)


if __name__ == '__main__':
    unittest.main() 